### ISSUE TITLE
Upgrade to 1.0

### ISSUE THREAD

**Issue by jorgebucaran** [lukejacksonn/hyperapp-firebase-auth#1]
Just a friendly reminder that [Hyperapp 1.0](https://hackernoon.com/introducing-hyperapp-1-0-dbf4229abfef) has officially hit the streets and this module is now using an older API. Time to upgrade! 👋 

See also: https://github.com/hyperapp/awesome/issues/18

**Comment by lukejacksonn** [comment]
All done! Updated demo: https://codepen.io/lukejacksonn/pen/xLBJoN

This was a trickier than the other upgrades.. at least it tested:

- Creating importable (module) state/actions wiring them up and passing them down the view.
- Subscribing to a stream and passing an action as a callback.

There are many other patterns, but this seemed most in-keeping with the router.

@JorgeBucaran is this implementation roughly how you would have done it?

**Comment by jorgebucaran** [comment]
@lukejacksonn LGTM! 👍
