### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by warwickgrigg** [lukejacksonn/hyperapp-firebase-auth#8]
Please would you add / grant a licence? Without a licence, then default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works.  [https://help.github.com/articles/licensing-a-repository/] (https://help.github.com/articles/licensing-a-repository/) ). I'd like to create an AWS auth for hyperapp derived from your code, please. May I suggest MIT licence, in keeping with hyperapp?

**Comment by lukejacksonn** [comment]
Sure thing! I just added a LICENSE file; MIT as you suggested. Hope that helps 👍 keep me posted if there is ever anything you have made with it that you can share.
